import { moneyToCents } from "@climb/ranking";
import { PrismaClient, SocialLinkType } from "../src/generated/client";

const prisma = new PrismaClient();

const categories = [
  { name: "Software Engineering", slug: "software-engineering" },
  { name: "AI / ML", slug: "ai-ml" },
  { name: "Founder", slug: "founder" },
  { name: "Startup", slug: "startup" },
  { name: "Product", slug: "product" },
  { name: "Design", slug: "design" },
  { name: "Marketing", slug: "marketing" },
  { name: "Finance", slug: "finance" },
  { name: "Creator", slug: "creator" },
  { name: "Student", slug: "student" },
  { name: "Open Source", slug: "open-source" },
  { name: "Other", slug: "other" },
] as const;

type SeedPerson = {
  email: string;
  username: string;
  fullName: string;
  headline: string;
  bio: string;
  categorySlug: (typeof categories)[number]["slug"];
  location: string;
  country: string;
  currentBid: string;
  totalViews: number;
  verified: boolean;
  hoursOnBoard: number;
  links: Partial<Record<SocialLinkType, string>>;
  rank24h: number;
  rank7d: number;
  bid24h: string;
  bid7d: string;
};

const people: SeedPerson[] = [
  {
    email: "maya.chen@climb.local",
    username: "maya-chen",
    fullName: "Maya Chen",
    headline: "Building evaluation harnesses for production LLM systems",
    bio: "Staff engineer working at the intersection of applied research and shipping. Previously scaled ranking infrastructure.",
    categorySlug: "ai-ml",
    location: "San Francisco",
    country: "US",
    currentBid: "421.00",
    totalViews: 1842,
    verified: true,
    hoursOnBoard: 36,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/maya-chen-climb",
      GITHUB: "https://github.com/mayachen",
      TWITTER: "https://x.com/mayachen",
      WEBSITE: "https://mayachen.dev",
    },
    rank24h: 4,
    rank7d: 18,
    bid24h: "280.00",
    bid7d: "90.00",
  },
  {
    email: "rahul.sharma@climb.local",
    username: "rahul-sharma",
    fullName: "Rahul Sharma",
    headline: "Founder. Twice shipped, once learned the hard way.",
    bio: "Building a new company after a 2019 acquisition. Obsessed with distribution and craft.",
    categorySlug: "founder",
    location: "Bengaluru",
    country: "IN",
    currentBid: "380.00",
    totalViews: 1203,
    verified: true,
    hoursOnBoard: 40,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/rahul-sharma-climb",
      TWITTER: "https://x.com/rahulbuilds",
      WEBSITE: "https://rahulsharma.co",
    },
    rank24h: 2,
    rank7d: 9,
    bid24h: "360.00",
    bid7d: "140.00",
  },
  {
    email: "priya.singh@climb.local",
    username: "priya-singh",
    fullName: "Priya Singh",
    headline: "AI engineer. Models in production, not just notebooks.",
    bio: "I take research papers to latency budgets. Currently focused on retrieval quality.",
    categorySlug: "ai-ml",
    location: "London",
    country: "GB",
    currentBid: "251.00",
    totalViews: 892,
    verified: true,
    hoursOnBoard: 28,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/priya-singh-climb",
      GITHUB: "https://github.com/priyasingh",
      PORTFOLIO: "https://priyasingh.ai",
    },
    rank24h: 10,
    rank7d: 21,
    bid24h: "120.00",
    bid7d: "40.00",
  },
  {
    email: "arjun.mehta@climb.local",
    username: "arjun-mehta",
    fullName: "Arjun Mehta",
    headline: "Product designer for ambitious tools",
    bio: "I design systems that make complex products feel inevitable.",
    categorySlug: "design",
    location: "Mumbai",
    country: "IN",
    currentBid: "220.00",
    totalViews: 720,
    verified: false,
    hoursOnBoard: 50,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/arjun-mehta-climb",
      PORTFOLIO: "https://arjunmehta.studio",
      TWITTER: "https://x.com/arjundesigns",
    },
    rank24h: 6,
    rank7d: 11,
    bid24h: "180.00",
    bid7d: "95.00",
  },
  {
    email: "sofia.alvarez@climb.local",
    username: "sofia-alvarez",
    fullName: "Sofia Alvarez",
    headline: "Product lead. Ship the loop, then the polish.",
    bio: "I run product for a 40-person team. Ex-growth, now systems.",
    categorySlug: "product",
    location: "Mexico City",
    country: "MX",
    currentBid: "198.00",
    totalViews: 640,
    verified: true,
    hoursOnBoard: 22,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/sofia-alvarez-climb",
      WEBSITE: "https://sofia.works",
    },
    rank24h: 8,
    rank7d: 16,
    bid24h: "150.00",
    bid7d: "55.00",
  },
  {
    email: "noah.brooks@climb.local",
    username: "noah-brooks",
    fullName: "Noah Brooks",
    headline: "Software engineer. Infrastructure that stays boring.",
    bio: "Distributed systems, Postgres, and the kind of reliability users never notice.",
    categorySlug: "software-engineering",
    location: "Austin",
    country: "US",
    currentBid: "175.00",
    totalViews: 1104,
    verified: false,
    hoursOnBoard: 70,
    links: {
      GITHUB: "https://github.com/noahbrooks",
      LINKEDIN: "https://www.linkedin.com/in/noah-brooks-climb",
      WEBSITE: "https://noahbrooks.dev",
    },
    rank24h: 5,
    rank7d: 7,
    bid24h: "170.00",
    bid7d: "130.00",
  },
  {
    email: "leila.hassan@climb.local",
    username: "leila-hassan",
    fullName: "Leila Hassan",
    headline: "Marketing for products that don't need to shout",
    bio: "Brand and lifecycle. I like quiet launches that compound.",
    categorySlug: "marketing",
    location: "Berlin",
    country: "DE",
    currentBid: "162.00",
    totalViews: 510,
    verified: false,
    hoursOnBoard: 18,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/leila-hassan-climb",
      TWITTER: "https://x.com/leilahassan",
    },
    rank24h: 14,
    rank7d: 22,
    bid24h: "80.00",
    bid7d: "25.00",
  },
  {
    email: "kenji.sato@climb.local",
    username: "kenji-sato",
    fullName: "Kenji Sato",
    headline: "Open source maintainer. Libraries used by millions.",
    bio: "I maintain tooling that other engineers forget is even there — which is the point.",
    categorySlug: "open-source",
    location: "Tokyo",
    country: "JP",
    currentBid: "151.00",
    totalViews: 2301,
    verified: true,
    hoursOnBoard: 90,
    links: {
      GITHUB: "https://github.com/kenjisato",
      TWITTER: "https://x.com/kenjisato",
      WEBSITE: "https://kenji.dev",
    },
    rank24h: 9,
    rank7d: 12,
    bid24h: "140.00",
    bid7d: "100.00",
  },
  {
    email: "amelia.ford@climb.local",
    username: "amelia-ford",
    fullName: "Amelia Ford",
    headline: "Creator. Essays on work, craft, and attention.",
    bio: "I write for operators who still care about taste.",
    categorySlug: "creator",
    location: "New York",
    country: "US",
    currentBid: "140.00",
    totalViews: 980,
    verified: true,
    hoursOnBoard: 15,
    links: {
      TWITTER: "https://x.com/ameliaford",
      WEBSITE: "https://ameliaford.com",
    },
    rank24h: 17,
    rank7d: 24,
    bid24h: "40.00",
    bid7d: "10.00",
  },
  {
    email: "david.okonkwo@climb.local",
    username: "david-okonkwo",
    fullName: "David Okonkwo",
    headline: "Finance. Operator first, spreadsheet second.",
    bio: "FP&A that actually influences the product roadmap.",
    categorySlug: "finance",
    location: "Lagos",
    country: "NG",
    currentBid: "128.00",
    totalViews: 404,
    verified: false,
    hoursOnBoard: 44,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/david-okonkwo-climb",
    },
    rank24h: 11,
    rank7d: 15,
    bid24h: "110.00",
    bid7d: "70.00",
  },
  {
    email: "hana.park@climb.local",
    username: "hana-park",
    fullName: "Hana Park",
    headline: "Student. Shipping anyway.",
    bio: "CS at KAIST. Interned twice. Building in public until someone notices for the right reasons.",
    categorySlug: "student",
    location: "Seoul",
    country: "KR",
    currentBid: "96.00",
    totalViews: 1330,
    verified: false,
    hoursOnBoard: 10,
    links: {
      GITHUB: "https://github.com/hanapark",
      TWITTER: "https://x.com/hanabuilds",
      PORTFOLIO: "https://hana.park.dev",
    },
    rank24h: 20,
    rank7d: 28,
    bid24h: "20.00",
    bid7d: "5.00",
  },
  {
    email: "lucas.meyer@climb.local",
    username: "lucas-meyer",
    fullName: "Lucas Meyer",
    headline: "Startup operator. Zero to something.",
    bio: "I join early, install process without killing speed, and leave when the company no longer needs me.",
    categorySlug: "startup",
    location: "Paris",
    country: "FR",
    currentBid: "88.00",
    totalViews: 355,
    verified: false,
    hoursOnBoard: 60,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/lucas-meyer-climb",
      WEBSITE: "https://lucasmeyer.co",
    },
    rank24h: 12,
    rank7d: 14,
    bid24h: "85.00",
    bid7d: "60.00",
  },
  {
    email: "nina.volkov@climb.local",
    username: "nina-volkov",
    fullName: "Nina Volkov",
    headline: "Designer of type, product, and the spaces between",
    bio: "Independent. I take fewer clients and do the work that lasts.",
    categorySlug: "design",
    location: "Amsterdam",
    country: "NL",
    currentBid: "77.00",
    totalViews: 612,
    verified: true,
    hoursOnBoard: 33,
    links: {
      PORTFOLIO: "https://ninavolkov.com",
      TWITTER: "https://x.com/ninavolkov",
    },
    rank24h: 13,
    rank7d: 19,
    bid24h: "65.00",
    bid7d: "30.00",
  },
  {
    email: "omar.farouk@climb.local",
    username: "omar-farouk",
    fullName: "Omar Farouk",
    headline: "Software engineer. Compilers, then APIs.",
    bio: "I like languages, slow thinking, and fast programs.",
    categorySlug: "software-engineering",
    location: "Cairo",
    country: "EG",
    currentBid: "64.00",
    totalViews: 288,
    verified: false,
    hoursOnBoard: 26,
    links: {
      GITHUB: "https://github.com/omarfarouk",
      LINKEDIN: "https://www.linkedin.com/in/omar-farouk-climb",
    },
    rank24h: 16,
    rank7d: 20,
    bid24h: "50.00",
    bid7d: "22.00",
  },
  {
    email: "elena.rossi@climb.local",
    username: "elena-rossi",
    fullName: "Elena Rossi",
    headline: "Founder of a small, stubborn company",
    bio: "Bootstrapped. Profitable. Still answering support on Sundays.",
    categorySlug: "founder",
    location: "Milan",
    country: "IT",
    currentBid: "59.00",
    totalViews: 271,
    verified: false,
    hoursOnBoard: 12,
    links: {
      WEBSITE: "https://elenarossi.com",
      LINKEDIN: "https://www.linkedin.com/in/elena-rossi-climb",
    },
    rank24h: 19,
    rank7d: 25,
    bid24h: "21.00",
    bid7d: "8.00",
  },
  {
    email: "james.okada@climb.local",
    username: "james-okada",
    fullName: "James Okada",
    headline: "Product. I write the spec the team actually wants",
    bio: "Ex-PM at two companies you have heard of. Now independent.",
    categorySlug: "product",
    location: "Toronto",
    country: "CA",
    currentBid: "52.00",
    totalViews: 198,
    verified: false,
    hoursOnBoard: 48,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/james-okada-climb",
      TWITTER: "https://x.com/jamesokada",
    },
    rank24h: 15,
    rank7d: 17,
    bid24h: "48.00",
    bid7d: "35.00",
  },
  {
    email: "aisha.rahman@climb.local",
    username: "aisha-rahman",
    fullName: "Aisha Rahman",
    headline: "Creator. Short films, long newsletters.",
    bio: "I make work about cities, software, and the people stuck between them.",
    categorySlug: "creator",
    location: "Dubai",
    country: "AE",
    currentBid: "44.00",
    totalViews: 740,
    verified: false,
    hoursOnBoard: 8,
    links: {
      TWITTER: "https://x.com/aisharahman",
      WEBSITE: "https://aisharahman.tv",
    },
    rank24h: 23,
    rank7d: 30,
    bid24h: "12.00",
    bid7d: "5.00",
  },
  {
    email: "theo.nguyen@climb.local",
    username: "theo-nguyen",
    fullName: "Theo Nguyen",
    headline: "Open source. Docs, then code.",
    bio: "I believe a library is only as good as the first ten minutes.",
    categorySlug: "open-source",
    location: "Ho Chi Minh City",
    country: "VN",
    currentBid: "39.00",
    totalViews: 456,
    verified: false,
    hoursOnBoard: 54,
    links: {
      GITHUB: "https://github.com/theonguyen",
      WEBSITE: "https://theo.dev",
    },
    rank24h: 18,
    rank7d: 23,
    bid24h: "30.00",
    bid7d: "18.00",
  },
  {
    email: "sara.lindqvist@climb.local",
    username: "sara-lindqvist",
    fullName: "Sara Lindqvist",
    headline: "Marketing. Narrative before channels.",
    bio: "I help technical companies sound like themselves.",
    categorySlug: "marketing",
    location: "Stockholm",
    country: "SE",
    currentBid: "33.00",
    totalViews: 167,
    verified: false,
    hoursOnBoard: 20,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/sara-lindqvist-climb",
      WEBSITE: "https://saralindqvist.com",
    },
    rank24h: 21,
    rank7d: 26,
    bid24h: "18.00",
    bid7d: "9.00",
  },
  {
    email: "ben.carter@climb.local",
    username: "ben-carter",
    fullName: "Ben Carter",
    headline: "Finance for companies that still make things",
    bio: "Treasury, fundraising, and saying no with a spreadsheet.",
    categorySlug: "finance",
    location: "Chicago",
    country: "US",
    currentBid: "27.00",
    totalViews: 143,
    verified: false,
    hoursOnBoard: 31,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/ben-carter-climb",
    },
    rank24h: 22,
    rank7d: 27,
    bid24h: "16.00",
    bid7d: "11.00",
  },
  {
    email: "yara.nasser@climb.local",
    username: "yara-nasser",
    fullName: "Yara Nasser",
    headline: "Student building a design practice in public",
    bio: "Third year. Internship next summer. A lot of Figma files named final-final.",
    categorySlug: "student",
    location: "Amman",
    country: "JO",
    currentBid: "21.00",
    totalViews: 502,
    verified: false,
    hoursOnBoard: 6,
    links: {
      PORTFOLIO: "https://yaranasser.design",
      TWITTER: "https://x.com/yaranasser",
    },
    rank24h: 26,
    rank7d: 32,
    bid24h: "7.00",
    bid7d: "5.00",
  },
  {
    email: "marcus.hale@climb.local",
    username: "marcus-hale",
    fullName: "Marcus Hale",
    headline: "Other. I don't fit the boxes and that's fine.",
    bio: "Researcher, occasional founder, mostly curious.",
    categorySlug: "other",
    location: "Cape Town",
    country: "ZA",
    currentBid: "18.00",
    totalViews: 121,
    verified: false,
    hoursOnBoard: 41,
    links: {
      WEBSITE: "https://marcushale.net",
      LINKEDIN: "https://www.linkedin.com/in/marcus-hale-climb",
    },
    rank24h: 24,
    rank7d: 29,
    bid24h: "12.00",
    bid7d: "6.00",
  },
  {
    email: "isla.macrae@climb.local",
    username: "isla-macrae",
    fullName: "Isla Macrae",
    headline: "Startup. First designer, then first hire.",
    bio: "I join when there are six people and a scary amount of conviction.",
    categorySlug: "startup",
    location: "Edinburgh",
    country: "GB",
    currentBid: "12.00",
    totalViews: 88,
    verified: false,
    hoursOnBoard: 14,
    links: {
      LINKEDIN: "https://www.linkedin.com/in/isla-macrae-climb",
      PORTFOLIO: "https://islamacrae.com",
    },
    rank24h: 25,
    rank7d: 31,
    bid24h: "8.00",
    bid7d: "5.00",
  },
  {
    email: "wei.tan@climb.local",
    username: "wei-tan",
    fullName: "Wei Tan",
    headline: "Software engineer. Quiet PRs, loud impact.",
    bio: "I work on developer tools. I want your build to be boringly fast.",
    categorySlug: "software-engineering",
    location: "Singapore",
    country: "SG",
    currentBid: "9.00",
    totalViews: 76,
    verified: false,
    hoursOnBoard: 5,
    links: {
      GITHUB: "https://github.com/weitan",
      LINKEDIN: "https://www.linkedin.com/in/wei-tan-climb",
    },
    rank24h: 27,
    rank7d: 33,
    bid24h: "5.00",
    bid7d: "5.00",
  },
];

const extraPeople: SeedPerson[] = [
  {
    email: "grace.okoro@climb.local",
    username: "grace-okoro",
    fullName: "Grace Okoro",
    headline: "Product designer. Interfaces that stay out of the way.",
    bio: "I design for operators who live in the product all day.",
    categorySlug: "design",
    location: "Accra",
    country: "GH",
    currentBid: "85.00",
    totalViews: 412,
    verified: false,
    hoursOnBoard: 29,
    links: { PORTFOLIO: "https://graceokoro.design", LINKEDIN: "https://www.linkedin.com/in/grace-okoro-climb" },
    rank24h: 16,
    rank7d: 24,
    bid24h: "60.00",
    bid7d: "20.00",
  },
  {
    email: "tom.reid@climb.local",
    username: "tom-reid",
    fullName: "Tom Reid",
    headline: "Software engineer. Postgres, queues, and calm deploys.",
    bio: "I like systems that fail obviously and recover quietly.",
    categorySlug: "software-engineering",
    location: "Denver",
    country: "US",
    currentBid: "71.00",
    totalViews: 265,
    verified: false,
    hoursOnBoard: 37,
    links: { GITHUB: "https://github.com/tomreid", WEBSITE: "https://tomreid.dev" },
    rank24h: 18,
    rank7d: 22,
    bid24h: "55.00",
    bid7d: "28.00",
  },
  {
    email: "meera.iyer@climb.local",
    username: "meera-iyer",
    fullName: "Meera Iyer",
    headline: "AI / ML. Evaluation before launch, always.",
    bio: "I measure models the way product measures conversion.",
    categorySlug: "ai-ml",
    location: "Hyderabad",
    country: "IN",
    currentBid: "68.00",
    totalViews: 388,
    verified: true,
    hoursOnBoard: 19,
    links: { GITHUB: "https://github.com/meeraiyer", LINKEDIN: "https://www.linkedin.com/in/meera-iyer-climb" },
    rank24h: 21,
    rank7d: 29,
    bid24h: "30.00",
    bid7d: "12.00",
  },
  {
    email: "felix.berg@climb.local",
    username: "felix-berg",
    fullName: "Felix Berg",
    headline: "Founder. One product, long horizon.",
    bio: "Building a boringly useful B2B tool. Profit is a feature.",
    categorySlug: "founder",
    location: "Zurich",
    country: "CH",
    currentBid: "61.00",
    totalViews: 190,
    verified: false,
    hoursOnBoard: 45,
    links: { WEBSITE: "https://felixberg.com", TWITTER: "https://x.com/felixberg" },
    rank24h: 17,
    rank7d: 20,
    bid24h: "58.00",
    bid7d: "40.00",
  },
  {
    email: "nora.klein@climb.local",
    username: "nora-klein",
    fullName: "Nora Klein",
    headline: "Marketing. Distribution as a craft.",
    bio: "I help technical teams get found without becoming a billboard.",
    categorySlug: "marketing",
    location: "Vienna",
    country: "AT",
    currentBid: "48.00",
    totalViews: 224,
    verified: false,
    hoursOnBoard: 16,
    links: { LINKEDIN: "https://www.linkedin.com/in/nora-klein-climb", WEBSITE: "https://noraklein.co" },
    rank24h: 25,
    rank7d: 33,
    bid24h: "18.00",
    bid7d: "8.00",
  },
  {
    email: "samir.khalil@climb.local",
    username: "samir-khalil",
    fullName: "Samir Khalil",
    headline: "Finance. Unit economics without the theater.",
    bio: "I install the numbers a founding team actually uses.",
    categorySlug: "finance",
    location: "Dubai",
    country: "AE",
    currentBid: "42.00",
    totalViews: 156,
    verified: false,
    hoursOnBoard: 27,
    links: { LINKEDIN: "https://www.linkedin.com/in/samir-khalil-climb" },
    rank24h: 24,
    rank7d: 31,
    bid24h: "22.00",
    bid7d: "10.00",
  },
  {
    email: "chloe.martin@climb.local",
    username: "chloe-martin",
    fullName: "Chloe Martin",
    headline: "Creator. Essays on making things that last.",
    bio: "I write for people who still care how the work feels.",
    categorySlug: "creator",
    location: "Montreal",
    country: "CA",
    currentBid: "36.00",
    totalViews: 501,
    verified: false,
    hoursOnBoard: 11,
    links: { TWITTER: "https://x.com/chloemakes", WEBSITE: "https://chloemartin.write" },
    rank24h: 28,
    rank7d: 36,
    bid24h: "14.00",
    bid7d: "6.00",
  },
  {
    email: "jonas.petrik@climb.local",
    username: "jonas-petrik",
    fullName: "Jonas Petrik",
    headline: "Open source. Small APIs, strong guarantees.",
    bio: "I maintain libraries that other people forget they depend on.",
    categorySlug: "open-source",
    location: "Vilnius",
    country: "LT",
    currentBid: "31.00",
    totalViews: 673,
    verified: true,
    hoursOnBoard: 62,
    links: { GITHUB: "https://github.com/jonaspetrik", WEBSITE: "https://jonas.dev" },
    rank24h: 23,
    rank7d: 27,
    bid24h: "28.00",
    bid7d: "19.00",
  },
  {
    email: "anya.kuznetsova@climb.local",
    username: "anya-kuznetsova",
    fullName: "Anya Kuznetsova",
    headline: "Student. Shipping before the syllabus catches up.",
    bio: "CS student. Internships, side projects, and a lot of coffee.",
    categorySlug: "student",
    location: "Kyiv",
    country: "UA",
    currentBid: "24.00",
    totalViews: 812,
    verified: false,
    hoursOnBoard: 9,
    links: { GITHUB: "https://github.com/anyakuz", TWITTER: "https://x.com/anyakuz" },
    rank24h: 32,
    rank7d: 40,
    bid24h: "8.00",
    bid7d: "5.00",
  },
  {
    email: "diego.ramos@climb.local",
    username: "diego-ramos",
    fullName: "Diego Ramos",
    headline: "Startup. First engineer, then the culture.",
    bio: "I join before the org chart exists and leave when it does.",
    categorySlug: "startup",
    location: "São Paulo",
    country: "BR",
    currentBid: "22.00",
    totalViews: 203,
    verified: false,
    hoursOnBoard: 21,
    links: { LINKEDIN: "https://www.linkedin.com/in/diego-ramos-climb", GITHUB: "https://github.com/diegoramos" },
    rank24h: 27,
    rank7d: 34,
    bid24h: "15.00",
    bid7d: "7.00",
  },
  {
    email: "ruth.adeyemi@climb.local",
    username: "ruth-adeyemi",
    fullName: "Ruth Adeyemi",
    headline: "Product. Specs people can actually build.",
    bio: "I write the document the team wanted last week.",
    categorySlug: "product",
    location: "Nairobi",
    country: "KE",
    currentBid: "19.00",
    totalViews: 177,
    verified: false,
    hoursOnBoard: 34,
    links: { LINKEDIN: "https://www.linkedin.com/in/ruth-adeyemi-climb", TWITTER: "https://x.com/ruthbuilds" },
    rank24h: 26,
    rank7d: 32,
    bid24h: "16.00",
    bid7d: "9.00",
  },
  {
    email: "pierre.dubois@climb.local",
    username: "pierre-dubois",
    fullName: "Pierre Dubois",
    headline: "Other. Researcher who ships.",
    bio: "I move ideas from papers into products that survive contact with users.",
    categorySlug: "other",
    location: "Lyon",
    country: "FR",
    currentBid: "16.00",
    totalViews: 94,
    verified: false,
    hoursOnBoard: 39,
    links: { WEBSITE: "https://pierredubois.net", GITHUB: "https://github.com/pierredubois" },
    rank24h: 29,
    rank7d: 35,
    bid24h: "11.00",
    bid7d: "6.00",
  },
  {
    email: "min.cho@climb.local",
    username: "min-cho",
    fullName: "Min Cho",
    headline: "Software engineer. Developer tools, relentlessly.",
    bio: "I want your feedback loop to be shorter than your coffee.",
    categorySlug: "software-engineering",
    location: "Seoul",
    country: "KR",
    currentBid: "14.00",
    totalViews: 310,
    verified: false,
    hoursOnBoard: 13,
    links: { GITHUB: "https://github.com/mincho", LINKEDIN: "https://www.linkedin.com/in/min-cho-climb" },
    rank24h: 30,
    rank7d: 38,
    bid24h: "7.00",
    bid7d: "5.00",
  },
  {
    email: "lara.schmidt@climb.local",
    username: "lara-schmidt",
    fullName: "Lara Schmidt",
    headline: "Design. Type, product, and the quiet parts.",
    bio: "Independent. Fewer clients, more care.",
    categorySlug: "design",
    location: "Hamburg",
    country: "DE",
    currentBid: "13.00",
    totalViews: 148,
    verified: false,
    hoursOnBoard: 17,
    links: { PORTFOLIO: "https://laraschmidt.studio", TWITTER: "https://x.com/laraschmidt" },
    rank24h: 31,
    rank7d: 37,
    bid24h: "9.00",
    bid7d: "5.00",
  },
  {
    email: "ibrahim.hassan@climb.local",
    username: "ibrahim-hassan",
    fullName: "Ibrahim Hassan",
    headline: "AI engineer. Latency budgets are a product decision.",
    bio: "I take models from notebooks to production SLAs.",
    categorySlug: "ai-ml",
    location: "Doha",
    country: "QA",
    currentBid: "11.00",
    totalViews: 221,
    verified: false,
    hoursOnBoard: 8,
    links: { GITHUB: "https://github.com/ibrahimh", LINKEDIN: "https://www.linkedin.com/in/ibrahim-hassan-climb" },
    rank24h: 34,
    rank7d: 42,
    bid24h: "6.00",
    bid7d: "5.00",
  },
  {
    email: "emma.walsh@climb.local",
    username: "emma-walsh",
    fullName: "Emma Walsh",
    headline: "Founder. Second company, fewer delusions.",
    bio: "I already made the expensive mistakes. Now I make cheaper ones.",
    categorySlug: "founder",
    location: "Dublin",
    country: "IE",
    currentBid: "10.00",
    totalViews: 132,
    verified: false,
    hoursOnBoard: 23,
    links: { WEBSITE: "https://emmawalsh.co", TWITTER: "https://x.com/emmawalsh" },
    rank24h: 33,
    rank7d: 39,
    bid24h: "7.00",
    bid7d: "5.00",
  },
  {
    email: "carlos.mendez@climb.local",
    username: "carlos-mendez",
    fullName: "Carlos Mendez",
    headline: "Product. Growth without dark patterns.",
    bio: "I design loops people do not regret joining.",
    categorySlug: "product",
    location: "Bogotá",
    country: "CO",
    currentBid: "8.00",
    totalViews: 99,
    verified: false,
    hoursOnBoard: 12,
    links: { LINKEDIN: "https://www.linkedin.com/in/carlos-mendez-climb" },
    rank24h: 35,
    rank7d: 41,
    bid24h: "6.00",
    bid7d: "5.00",
  },
  {
    email: "yuki.tanaka@climb.local",
    username: "yuki-tanaka",
    fullName: "Yuki Tanaka",
    headline: "Open source. Documentation as the product.",
    bio: "If the first ten minutes fail, the library failed.",
    categorySlug: "open-source",
    location: "Osaka",
    country: "JP",
    currentBid: "7.00",
    totalViews: 440,
    verified: false,
    hoursOnBoard: 51,
    links: { GITHUB: "https://github.com/yukitanaka", WEBSITE: "https://yuki.dev" },
    rank24h: 36,
    rank7d: 43,
    bid24h: "6.00",
    bid7d: "5.00",
  },
  {
    email: "fatima.zahra@climb.local",
    username: "fatima-zahra",
    fullName: "Fatima Zahra",
    headline: "Marketing for products that do one thing well.",
    bio: "Narrative first. Channels second.",
    categorySlug: "marketing",
    location: "Casablanca",
    country: "MA",
    currentBid: "6.00",
    totalViews: 118,
    verified: false,
    hoursOnBoard: 7,
    links: { LINKEDIN: "https://www.linkedin.com/in/fatima-zahra-climb", WEBSITE: "https://fatimazahra.co" },
    rank24h: 38,
    rank7d: 45,
    bid24h: "5.00",
    bid7d: "5.00",
  },
  {
    email: "alex.petrov@climb.local",
    username: "alex-petrov",
    fullName: "Alex Petrov",
    headline: "Student building in public until it sticks.",
    bio: "Second year. Side projects with real users, not just GitHub stars.",
    categorySlug: "student",
    location: "Sofia",
    country: "BG",
    currentBid: "5.00",
    totalViews: 275,
    verified: false,
    hoursOnBoard: 4,
    links: { GITHUB: "https://github.com/alexp", TWITTER: "https://x.com/alexpbuilds" },
    rank24h: 40,
    rank7d: 48,
    bid24h: "5.00",
    bid7d: "5.00",
  },
];

const roster = [...people, ...extraPeople];

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

async function main() {
  await prisma.analyticsEvent.deleteMany();
  await prisma.activity.deleteMany();
  await prisma.providerWebhookEvent.deleteMany();
  await prisma.linkClick.deleteMany();
  await prisma.profileView.deleteMany();
  await prisma.rankSnapshot.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.bid.deleteMany();
  await prisma.socialLink.deleteMany();
  await prisma.person.deleteMany();
  await prisma.user.deleteMany();
  await prisma.category.deleteMany();

  const createdCategories = await Promise.all(
    categories.map((category) => prisma.category.create({ data: category })),
  );
  const categoryBySlug = new Map(createdCategories.map((category) => [category.slug, category]));

  const generated: SeedPerson[] = Array.from({ length: 16 }, (_, index) => {
    const n = index + 1;
    const slugs = categories.map((category) => category.slug);
    const slug = slugs[index % slugs.length]!;
    return {
      email: `climber${n}@climb.local`,
      username: `climber-${n}`,
      fullName: `Climber ${n}`,
      headline: "On the board. Building in public.",
      bio: "Seeded listing so the lower ranks stay populated.",
      categorySlug: slug,
      location: "Remote",
      country: "US",
      currentBid: "5.00",
      totalViews: 20 + n * 3,
      verified: false,
      hoursOnBoard: 2 + n,
      links: { WEBSITE: `https://climber${n}.example` },
      rank24h: 44 + n,
      rank7d: 50 + n,
      bid24h: "5.00",
      bid7d: "5.00",
    };
  });

  const seedPeople = [...roster, ...generated];
  const createdIds: { id: string; currentBid: number; currentBidAt: Date }[] = [];

  for (const person of seedPeople) {
    const category = categoryBySlug.get(person.categorySlug);
    if (!category) throw new Error(`Missing category ${person.categorySlug}`);

    const createdAt = hoursAgo(person.hoursOnBoard);
    const currentBidAt = hoursAgo(Math.max(1, Math.round(person.hoursOnBoard / 4)));
    const currentBid = moneyToCents(person.currentBid);
    const bid24h = moneyToCents(person.bid24h);
    const bid7d = moneyToCents(person.bid7d);

    const user = await prisma.user.create({
      data: {
        email: person.email,
        name: person.fullName,
        createdAt,
        updatedAt: currentBidAt,
      },
    });

    const created = await prisma.person.create({
      data: {
        userId: user.id,
        username: person.username,
        fullName: person.fullName,
        headline: person.headline,
        bio: person.bio,
        categoryId: category.id,
        location: person.location,
        country: person.country,
        currentBid,
        currentBidAt,
        totalViews: person.totalViews,
        verified: person.verified,
        createdAt,
        updatedAt: currentBidAt,
        socialLinks: {
          create: Object.entries(person.links).map(([type, url]) => ({
            type: type as SocialLinkType,
            url,
            createdAt,
          })),
        },
        bids: {
          create: [
            {
              userId: user.id,
              targetBidCents: bid7d,
              chargeAmountCents: bid7d,
              status: "COMPLETED",
              createdAt: hoursAgo(24 * 7),
            },
            {
              userId: user.id,
              targetBidCents: bid24h,
              chargeAmountCents: bid24h,
              status: "COMPLETED",
              createdAt: hoursAgo(20),
            },
            {
              userId: user.id,
              targetBidCents: currentBid,
              chargeAmountCents: currentBid - bid24h > 0 ? currentBid - bid24h : currentBid,
              status: "COMPLETED",
              createdAt: currentBidAt,
            },
          ],
        },
        snapshots: {
          create: [
            {
              rank: person.rank7d,
              bid: bid7d,
              createdAt: hoursAgo(24 * 7),
            },
            {
              rank: person.rank24h,
              bid: bid24h,
              createdAt: hoursAgo(24),
            },
          ],
        },
      },
    });

    createdIds.push({ id: created.id, currentBid, currentBidAt });
  }

  const ranked = [...createdIds].sort((a, b) => {
    if (b.currentBid !== a.currentBid) return b.currentBid - a.currentBid;
    return a.currentBidAt.getTime() - b.currentBidAt.getTime();
  });

  await prisma.activity.createMany({
    data: ranked.map((person, index) => ({
      personId: person.id,
      type: index < 8 ? "RAISED" : "JOINED",
      amount: person.currentBid,
      rank: index + 1,
      createdAt: person.currentBidAt,
    })),
  });

  console.log(`Seeded ${seedPeople.length} people across ${categories.length} categories.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
